pizzas/urls.py
"""Defines URL patterns for pizzas."""
from django.urls import path
from . import views

app_name="pizzas"

urlpatterns = [
  # Home page
  path('home', views.home, name='home'),
  # Pizza list.
  path('', views.pizzas, name='pizzas'),
  # Pizza order
  path('<int:pizza_id>/order/', views.order, name='order'),
  # Pizza details page
  path('<int:pizza_id>/', views.pizza, name='pizza'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import include, path

app_name="pizzeria"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pizzas/', include('pizzas.urls')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path
from django.contrib.auth.views import login
from . import views

app_name="users"

urlpatterns = [
  # Login page
  path('login/', login, {'template_name': 'users/login.html'}, name='login'),
  # Logout page
  path('logout/', views.logout_view, name='logout'),
  # Registration page
  path('register/', views.register, name='register'),
]

pizzas/models.py
from django.db import models

class Pizza(models.Model):
  name = models.CharField(max_length=200)
  created_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.name

class Topping(models.Model):
  name = models.CharField(max_length=200)
  pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.name

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms

class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = 'Username',
        max_length = 32
    )
    email = forms.CharField(
        required = True,
        label = 'Email',
        max_length = 32,
    )
    password = forms.RegexField(
        regex = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$',
        required = True,
        label = 'Password',
        max_length = 32,
        widget = forms.PasswordInput()
    )
    password_two = forms.RegexField(
        regex = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$',
        required = True,
        label = 'Password (Again)',
        max_length = 32,
        widget = forms.PasswordInput()
    )
    first_name = forms.CharField(
        required = True,
        label = 'First name',
        max_length = 32
    )
    last_name = forms.CharField(
        required = True,
        label = 'Last name',
        max_length = 32
    )
    phone_number = forms.CharField(
        required = True,
        label = 'Phone',
        max_length = 20
    )
    address = forms.CharField(
        required = True,
        label = 'Address',
        max_length = 32
    )
    address_line_two = forms.CharField(
        required = False,
        label = 'Address (Line 2)',
        max_length = 32
    )
    town = forms.CharField(
        required = True,
        label = 'Town',
        max_length = 32
    )
    zipcode = forms.CharField(
        required = True,
        label = 'Zipcode',
        max_length = 5
    )
    state = forms.CharField(
        required = True,
        label = 'State',
        max_length = 2
    )

pizzas/views.py
from django.shortcuts import render
from .models import Pizza
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def home(request):
  """The home page for Pizza"""
  return render(request, 'pizzas/index.html')


def pizzas(request):
  """Show all pizzas."""
  pizzas = Pizza.objects.all()
  context = {'pizzas': pizzas}
  return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
  """Show a single pizza and all its toppings."""
  pizza = Pizza.objects.get(id=pizza_id)
  toppings = pizza.topping_set.all()
  context = {'pizza': pizza, 'toppings': toppings}
  return render(request, 'pizzas/pizza.html', context)

def order(request, pizza_id):
  if request.user.is_authenticated:
    """Order a pizza"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/order.html', context)
  else:
    return HttpResponseRedirect(reverse('users:login'))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django import forms
from .forms import UserRegistrationForm

def logout_view(request):
  """Log the user out."""
  logout(request)
  return HttpResponseRedirect(reverse('pizzas:pizzas'))

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email =  userObj['email']
            password =  userObj['password']
            password2 = userObj['password_two']
            if not (User.objects.filter(username=username).exists()
              or User.objects.filter(email=email).exists()
              or password != password2):
                User.objects.create_user(username, email, password)
                user = authenticate(username = username, password = password)
                login(request, user)
                return HttpResponseRedirect(reverse('pizzas:pizzas'))
            else:
                raise forms.ValidationError('Validation failed.')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form' : form})

pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:home' %}">Home</a>
  <br>
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
  <br>
  {% if user.is_authenticated %}
    Hello, {{ user.username }}. <a href="{% url 'users:logout' %}">Logout</a>
  {% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <br>
    <a href="{% url 'users:login' %}">Login</a>
  {% endif %}
</p>

{% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% block content %}
  <p>Pizza Land</p>

  <p>Your home for the best pizza!</p>
{% endblock content %}

pizzas/templates/pizzas/order.html
{% extends 'pizzas/base.html' %}
{% block content %}
  <p>ORDER PLACED</p>
  <br>
  <p>Pizza: {{ pizza }}</p>
  <p>Toppings:</p>
  <ul>
    {% for topping in toppings %}
      <li>
        <p>{{ topping.name|linebreaks }}</p>
      </li>
    {% empty %}
      <li>
        There are no toppings for this pizza yet.
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}
{% block content %}
  <p>Pizza: {{ pizza }}</p>
  <p>Toppings:</p>
  <ul>
    {% for topping in toppings %}
      <li>
        <p>{{ topping.name|linebreaks }}</p>
      </li>
    {% empty %}
      <li>
        There are no toppings for this pizza yet.
      </li>
    {% endfor %}
  </ul>
  <form name="create_order" method="post" action="{% url 'pizzas:order' pizza.id %}">
    {% csrf_token %}
    <input type="submit" value="Order" />
  </form>
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}
{% block content %}
<p>Pizzas</p>
  <ul>
    {% for pizza in pizzas %}
      <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    {% empty %}
      <li>No pizzas have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

users/templates/users/login.html
{% extends "pizzas/base.html" %}

{% block content %}
  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Login</button>
    <input type="hidden" name="next" value="{% url 'pizzas:pizzas' %}" />
  </form>
{% endblock content %}

users/templates/users/register.html
{% extends "pizzas/base.html" %}

{% block content %}
  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Register</button>
    <input type="hidden" name="next" value="{% url 'pizzas:pizzas' %}" />
  </form>
{% endblock content %}